execution:
  engine: prefect

auth:
  enabled: false

db:
  url: "postgresql+asyncpg://postgres:postgres@localhost:5432/finetune"
  echo: false
  auto_create: false

storage:
  kind: minio

k8s:
  namespace: "finetune"
  incluster: true
  kubeconfig: null
