app:
  env: dev

execution:
  engine: prefect

db:
  echo: false
  auto_create: false

storage:
  kind: minio

k8s:
  namespace: "finetune"
  incluster: true
  kubeconfig: null

sc:
  data_provider:
    container_memory_limit_mb: 6144
    service_headroom_mb: 512
