app:
  env: pre-release
  frontend_url: ""

execution:
  engine: prefect

db:
  url: ""
  echo: false
  auto_create: false

storage:
  kind: minio
  minio:
    endpoint: ""
    access_key: ""
    secret_key: ""

k8s:
  namespace: "finetune"
  incluster: false
  kubeconfig: null

prefect:
  api_url: ""
  ui_url: ""

label_studio:
  url: ""
  external_url: ""
  api_key: ""
  database_url: ""

auth:
  jwt_secret_key: ""

oauth:
  enabled: false
  state_secret: ""
