app:
  env: prod

execution:
  engine: local

db:
  url: "postgresql+asyncpg://postgres:postgres@localhost:5432/finetune"
  echo: false
  auto_create: false

storage:
  kind: minio

k8s:
  namespace: "finetune"
  incluster: false
  kubeconfig: null

oauth:
  enabled: false
