app:
  env: prod

execution:
  engine: prefect

logging:
  level: WARNING

db:
  echo: false
  auto_create: false

storage:
  kind: minio

k8s:
  namespace: "finetune"
  incluster: false
  kubeconfig: null

oauth:
  enabled: false

sc:
  data_provider:
    worker_count: 4
    container_memory_limit_mb: 6144
    service_headroom_mb: 512
