[project]
name = "online-finetune-platform"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["mypy-protobuf==5.1.0"]

[tool.uv]
concurrent-downloads = 4

[tool.uv.extra-build-dependencies]
antlr4-python3-runtime = ["setuptools"]

[tool.uv.workspace]
members = [
  "apps/api",
  "libs/ml",
  "libs/platform-runtime",
  "libs/python-sdk",
  "libs/protos",
  "libs/seedmaker",
]

[tool.uv.sources]
seedmaker = { workspace = true }
finetune-ml = { workspace = true }
finetune-api = { workspace = true }

[dependency-groups]
dev = [
  "boto3>=1.43.9",
  "fastapi[all]>=0.135.2",
  "finetune-api[gpu]",
  "finetune-ml",
  "grpcio-tools==1.80.0",
  "mkdocs==1.6.1",
  "omegaconf>=2.3.0",
  "pytest>=9.0.2",
  "pytest-asyncio>=1.3.0",
  "pytest-timeout>=2.4.0",
  "seedmaker",
  "torch>=2.9.1",
]

[tool.ty.src]
exclude = [
  "apps/api/app/shared/generated/**",
  "apps/api/tests/**",
  "apps/api/alembic/**",
]

[tool.pyright]
extraPaths = ["libs/platform-runtime/src", "libs/ml"]

[tool.ruff]
exclude = [
  "apps/api/app/shared/generated/",
  "apps/api/tests/",
  "apps/api/alembic/",
  "libs/protos/src/proto_stubs/",
]


[tool.pytest.ini_options]
timeout = 180
