from __future__ import annotations

import os
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TypeAlias

import pyarrow as pa
import pyarrow.parquet as pq

ROW_INDEX_COLUMN = "__row_index"

PathInput: TypeAlias = str | os.PathLike[str]
ParquetPaths: TypeAlias = PathInput | Sequence[PathInput]


@dataclass(frozen=True, slots=True)
class ParquetSource:
    path: Path
    schema: pa.Schema
    row_count: int
    row_group_sizes: tuple[int, ...]


def inspect_parquet_sources(
    paths: ParquetPaths,
    *,
    columns: Sequence[str] | None,
) -> tuple[tuple[ParquetSource, ...], tuple[str, ...] | None]:
    normalized_paths = _normalize_paths(paths)
    normalized_columns = _normalize_columns(columns)
    sources: list[ParquetSource] = []

    for path in normalized_paths:
        if not path.is_file():
            raise FileNotFoundError(f"Parquet input does not exist: {path}")
        try:
            parquet_file = pq.ParquetFile(path)
        except (OSError, pa.ArrowException) as exc:
            raise ValueError(f"Input is not a readable Parquet file: {path}") from exc

        schema = parquet_file.schema_arrow
        if ROW_INDEX_COLUMN in schema.names:
            raise ValueError(
                f"Parquet input contains reserved column {ROW_INDEX_COLUMN!r}: {path}. "
                "The Parquet loaders generate this index from physical row order."
            )
        if normalized_columns is not None:
            missing = set(normalized_columns).difference(schema.names)
            if missing:
                names = ", ".join(sorted(missing))
                raise ValueError(f"Parquet input {path} is missing columns: {names}")

        metadata = parquet_file.metadata
        sources.append(
            ParquetSource(
                path=path,
                schema=schema,
                row_count=metadata.num_rows,
                row_group_sizes=tuple(
                    metadata.row_group(index).num_rows
                    for index in range(metadata.num_row_groups)
                ),
            )
        )

    _validate_compatible_schemas(tuple(sources), normalized_columns)
    return tuple(sources), normalized_columns


def selected_schema(
    source: ParquetSource,
    columns: tuple[str, ...] | None,
) -> pa.Schema:
    if columns is None:
        return source.schema
    return pa.schema([source.schema.field(name) for name in columns])


def _normalize_paths(paths: ParquetPaths) -> tuple[Path, ...]:
    if isinstance(paths, (str, os.PathLike)):
        normalized = (Path(paths),)
    else:
        normalized = tuple(Path(path) for path in paths)
    if not normalized:
        raise ValueError("At least one Parquet input path is required")
    return normalized


def _normalize_columns(columns: Sequence[str] | None) -> tuple[str, ...] | None:
    if columns is None:
        return None
    normalized = tuple(columns)
    if not normalized:
        raise ValueError("columns must be None or a non-empty sequence")
    if ROW_INDEX_COLUMN in normalized:
        raise ValueError(
            f"{ROW_INDEX_COLUMN!r} is generated by the Parquet loader and must not "
            "be requested from the input"
        )
    if len(set(normalized)) != len(normalized):
        raise ValueError("columns must not contain duplicates")
    return normalized


def _validate_compatible_schemas(
    sources: tuple[ParquetSource, ...],
    columns: tuple[str, ...] | None,
) -> None:
    expected = selected_schema(sources[0], columns)
    for source in sources[1:]:
        actual = selected_schema(source, columns)
        if not expected.equals(actual, check_metadata=False):
            raise ValueError(
                "Parquet inputs have incompatible selected schemas: "
                f"{sources[0].path} != {source.path}"
            )
