from __future__ import annotations

from sampling_rules.errors import (
    InsufficientPopulationError,
    InvalidSamplingRuleError,
    MissingFieldError,
    SamplingRuleError,
)
from sampling_rules.models import (
    Condition,
    ConditionalLimitRule,
    ConditionOperator,
    ConditionSet,
    ExtraFilterRule,
    GroupQuota,
    GroupQuotaRule,
    GroupTarget,
    MatchMode,
    QuotaUnit,
    Rounding,
    RuleStage,
    SamplingPlan,
    SamplingProgram,
    SamplingResult,
    SamplingRule,
    ShortfallPolicy,
    TotalLimitRule,
)
from sampling_rules.planner import plan_group_quota
from sampling_rules.recipes import (
    adder_count_program,
    clipped_log10_quota,
    clustered_count_program,
    clustered_ratio_program,
    per_die_cap_program,
    prediction_log_quota_program,
)
from sampling_rules.sampler import DEFAULT_SAMPLING_SEED, execute_sampling, sample
from sampling_rules.spatial import (
    DYNAMIC_ADDER_DISTANCE_FIELD,
    DYNAMIC_ADDER_FIELD,
    DYNAMIC_ADDER_REFERENCE_INDEX_FIELD,
    DYNAMIC_CLUSTER_FIELD,
    DYNAMIC_CLUSTER_ID_FIELD,
    DYNAMIC_CLUSTER_NEIGHBOR_COUNT_FIELD,
    DYNAMIC_CLUSTER_ROLE_FIELD,
    AdderMatchMode,
    ClusterPointRole,
    DynamicAdderConfig,
    DynamicAdderResult,
    DynamicClusterConfig,
    DynamicClusterResult,
    compute_dynamic_adders,
    compute_dynamic_clusters,
    enrich_rows_with_dynamic_spatial_features,
)

__all__ = [
    "Condition",
    "ConditionalLimitRule",
    "ConditionOperator",
    "ConditionSet",
    "DEFAULT_SAMPLING_SEED",
    "DYNAMIC_ADDER_DISTANCE_FIELD",
    "DYNAMIC_ADDER_FIELD",
    "DYNAMIC_ADDER_REFERENCE_INDEX_FIELD",
    "DYNAMIC_CLUSTER_FIELD",
    "DYNAMIC_CLUSTER_ID_FIELD",
    "DYNAMIC_CLUSTER_NEIGHBOR_COUNT_FIELD",
    "DYNAMIC_CLUSTER_ROLE_FIELD",
    "AdderMatchMode",
    "ClusterPointRole",
    "DynamicAdderConfig",
    "DynamicAdderResult",
    "DynamicClusterConfig",
    "DynamicClusterResult",
    "ExtraFilterRule",
    "GroupQuota",
    "GroupQuotaRule",
    "GroupTarget",
    "InsufficientPopulationError",
    "InvalidSamplingRuleError",
    "MatchMode",
    "MissingFieldError",
    "QuotaUnit",
    "Rounding",
    "RuleStage",
    "SamplingPlan",
    "SamplingProgram",
    "SamplingResult",
    "SamplingRule",
    "SamplingRuleError",
    "ShortfallPolicy",
    "TotalLimitRule",
    "adder_count_program",
    "clipped_log10_quota",
    "clustered_count_program",
    "clustered_ratio_program",
    "compute_dynamic_adders",
    "compute_dynamic_clusters",
    "enrich_rows_with_dynamic_spatial_features",
    "execute_sampling",
    "per_die_cap_program",
    "plan_group_quota",
    "prediction_log_quota_program",
    "sample",
]
