# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"6\n\x0c\x45mbedRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"I\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x11\n\tdimension\x18\x03 \x01(\x05\"7\n\x11\x45mbedBatchRequest\x12\x0e\n\x06images\x18\x01 \x03(\x0c\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"B\n\x12\x45mbedBatchResponse\x12,\n\nembeddings\x18\x01 \x03(\x0b\x32\x18.embedding.EmbedResponse\"\x0f\n\rHealthRequest\"5\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t2\xd8\x01\n\x10\x45mbeddingService\x12:\n\x05\x45mbed\x12\x17.embedding.EmbedRequest\x1a\x18.embedding.EmbedResponse\x12I\n\nEmbedBatch\x12\x1c.embedding.EmbedBatchRequest\x1a\x1d.embedding.EmbedBatchResponse\x12=\n\x06Health\x12\x18.embedding.HealthRequest\x1a\x19.embedding.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=30
  _globals['_EMBEDREQUEST']._serialized_end=84
  _globals['_EMBEDRESPONSE']._serialized_start=86
  _globals['_EMBEDRESPONSE']._serialized_end=159
  _globals['_EMBEDBATCHREQUEST']._serialized_start=161
  _globals['_EMBEDBATCHREQUEST']._serialized_end=216
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=218
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=284
  _globals['_HEALTHREQUEST']._serialized_start=286
  _globals['_HEALTHREQUEST']._serialized_end=301
  _globals['_HEALTHRESPONSE']._serialized_start=303
  _globals['_HEALTHRESPONSE']._serialized_end=356
  _globals['_EMBEDDINGSERVICE']._serialized_start=359
  _globals['_EMBEDDINGSERVICE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
