FROM golang:1.26-alpine

RUN apk add --no-cache ca-certificates

ENV GOBIN=/opt/proto-tools/bin
ENV PATH=/opt/proto-tools/bin:/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin

RUN mkdir -p /opt/proto-tools/bin /vendor/go

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.0

WORKDIR /vendor/image-parser
COPY services/image-parser/go.mod services/image-parser/go.sum ./
RUN GOMODCACHE=/vendor/go/pkg/mod go mod download
