/**
 * Frontend-only UI helper types.
 * These are NOT generated by Orval — they are frontend-specific shapes
 * used by composables, API client helpers, and UI components.
 */
import type { Dataset } from "@/generated/orval/models/dataset";
import type { Sample } from "@/generated/orval/models/sample";
import type { Annotation } from "@/generated/orval/models/annotation";

export interface FetchSampleSliceOptions {
  offset?: number;
  limit?: number;
  label?: string | null;
  orderBy?: string;
  sampleIds?: string[] | null;
}

export type ScheduleStatus = "active" | "paused";

export interface DatasetExport {
  dataset: Dataset;
  samples: Sample[];
  annotations: Annotation[];
}

export interface ExportFormatItem {
  format_id: string;
}
