"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HealthRequest = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___HealthResponse = HealthResponse

@typing.final
class GetImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    PREFIX_FIELD_NUMBER: builtins.int
    CACHE_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    key: builtins.str
    prefix: builtins.str
    cache: builtins.bool
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        key: builtins.str = ...,
        prefix: builtins.str = ...,
        cache: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket", b"bucket", "cache", b"cache", "key", b"key", "prefix", b"prefix"]) -> None: ...

global___GetImageRequest = GetImageRequest

@typing.final
class GetImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    filename: builtins.str
    width: builtins.int
    height: builtins.int
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
        filename: builtins.str = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filename", b"filename", "height", b"height", "image_data", b"image_data", "width", b"width"]) -> None: ...

global___GetImageResponse = GetImageResponse

@typing.final
class SpriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    PREFIXES_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    CACHE_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    key: builtins.str
    size: builtins.int
    cache: builtins.bool
    @property
    def prefixes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        key: builtins.str = ...,
        prefixes: collections.abc.Iterable[builtins.str] | None = ...,
        size: builtins.int = ...,
        cache: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket", b"bucket", "cache", b"cache", "key", b"key", "prefixes", b"prefixes", "size", b"size"]) -> None: ...

global___SpriteRequest = SpriteRequest

@typing.final
class SpriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    width: builtins.int
    height: builtins.int
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["height", b"height", "image_data", b"image_data", "width", b"width"]) -> None: ...

global___SpriteResponse = SpriteResponse

@typing.final
class V2SpriteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUCKET_FIELD_NUMBER: builtins.int
    RECORD_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    bucket: builtins.str
    record: builtins.str
    size: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        bucket: builtins.str = ...,
        record: builtins.str = ...,
        items: collections.abc.Iterable[builtins.str] | None = ...,
        size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bucket", b"bucket", "items", b"items", "record", b"record", "size", b"size"]) -> None: ...

global___V2SpriteRequest = V2SpriteRequest

@typing.final
class V2SpriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    width: builtins.int
    height: builtins.int
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["height", b"height", "image_data", b"image_data", "width", b"width"]) -> None: ...

global___V2SpriteResponse = V2SpriteResponse

@typing.final
class GetScImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    DEFECT_ID_FIELD_NUMBER: builtins.int
    IMAGE_TYPE_FIELD_NUMBER: builtins.int
    REVIEW_IMAGE_ID_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    defect_id: builtins.str
    image_type: builtins.str
    review_image_id: builtins.int
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        defect_id: builtins.str = ...,
        image_type: builtins.str = ...,
        review_image_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defect_id", b"defect_id", "image_type", b"image_type", "inspection_time", b"inspection_time", "review_image_id", b"review_image_id", "wafer_key", b"wafer_key"]) -> None: ...

global___GetScImageRequest = GetScImageRequest

@typing.final
class GetScImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    content_type: builtins.str
    def __init__(
        self,
        *,
        image_data: builtins.bytes = ...,
        content_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "image_data", b"image_data"]) -> None: ...

global___GetScImageResponse = GetScImageResponse

@typing.final
class ScImageRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFECT_ID_FIELD_NUMBER: builtins.int
    IMAGE_TYPE_FIELD_NUMBER: builtins.int
    REVIEW_IMAGE_ID_FIELD_NUMBER: builtins.int
    defect_id: builtins.str
    image_type: builtins.str
    review_image_id: builtins.int
    def __init__(
        self,
        *,
        defect_id: builtins.str = ...,
        image_type: builtins.str = ...,
        review_image_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defect_id", b"defect_id", "image_type", b"image_type", "review_image_id", b"review_image_id"]) -> None: ...

global___ScImageRef = ScImageRef

@typing.final
class BatchGetScImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    IMAGES_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    @property
    def images(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ScImageRef]: ...
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        images: collections.abc.Iterable[global___ScImageRef] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["images", b"images", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]) -> None: ...

global___BatchGetScImageRequest = BatchGetScImageRequest

@typing.final
class ScImageResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFECT_ID_FIELD_NUMBER: builtins.int
    IMAGE_TYPE_FIELD_NUMBER: builtins.int
    IMAGE_DATA_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    defect_id: builtins.str
    image_type: builtins.str
    image_data: builtins.bytes
    content_type: builtins.str
    error: builtins.str
    def __init__(
        self,
        *,
        defect_id: builtins.str = ...,
        image_type: builtins.str = ...,
        image_data: builtins.bytes = ...,
        content_type: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "defect_id", b"defect_id", "error", b"error", "image_data", b"image_data", "image_type", b"image_type"]) -> None: ...

global___ScImageResult = ScImageResult

@typing.final
class BatchGetScImageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULTS_FIELD_NUMBER: builtins.int
    @property
    def results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ScImageResult]: ...
    def __init__(
        self,
        *,
        results: collections.abc.Iterable[global___ScImageResult] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["results", b"results"]) -> None: ...

global___BatchGetScImageResponse = BatchGetScImageResponse

@typing.final
class WarmScCacheRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    DEFECT_IDS_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    @property
    def defect_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        defect_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defect_ids", b"defect_ids", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]) -> None: ...

global___WarmScCacheRequest = WarmScCacheRequest

@typing.final
class WarmScCacheResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    ZIPS_WARMED_FIELD_NUMBER: builtins.int
    status: builtins.str
    zips_warmed: builtins.int
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        zips_warmed: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "zips_warmed", b"zips_warmed"]) -> None: ...

global___WarmScCacheResponse = WarmScCacheResponse
