# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_stubs.imageparser.v1 import service_pb2 as imageparser_dot_v1_dot_service__pb2


class ImageParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/imageparser.v1.ImageParser/Health',
                request_serializer=imageparser_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.HealthResponse.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/imageparser.v1.ImageParser/GetImage',
                request_serializer=imageparser_dot_v1_dot_service__pb2.GetImageRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.GetImageResponse.FromString,
                )
        self.Sprite = channel.unary_unary(
                '/imageparser.v1.ImageParser/Sprite',
                request_serializer=imageparser_dot_v1_dot_service__pb2.SpriteRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.SpriteResponse.FromString,
                )
        self.V2Sprite = channel.unary_unary(
                '/imageparser.v1.ImageParser/V2Sprite',
                request_serializer=imageparser_dot_v1_dot_service__pb2.V2SpriteRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.V2SpriteResponse.FromString,
                )
        self.GetScImage = channel.unary_unary(
                '/imageparser.v1.ImageParser/GetScImage',
                request_serializer=imageparser_dot_v1_dot_service__pb2.GetScImageRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.GetScImageResponse.FromString,
                )


class ImageParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sprite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def V2Sprite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.HealthRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.HealthResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.GetImageRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.GetImageResponse.SerializeToString,
            ),
            'Sprite': grpc.unary_unary_rpc_method_handler(
                    servicer.Sprite,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.SpriteRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.SpriteResponse.SerializeToString,
            ),
            'V2Sprite': grpc.unary_unary_rpc_method_handler(
                    servicer.V2Sprite,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.V2SpriteRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.V2SpriteResponse.SerializeToString,
            ),
            'GetScImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScImage,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.GetScImageRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.GetScImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageparser.v1.ImageParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageparser.v1.ImageParser/Health',
            imageparser_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageparser.v1.ImageParser/GetImage',
            imageparser_dot_v1_dot_service__pb2.GetImageRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.GetImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sprite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageparser.v1.ImageParser/Sprite',
            imageparser_dot_v1_dot_service__pb2.SpriteRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.SpriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def V2Sprite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageparser.v1.ImageParser/V2Sprite',
            imageparser_dot_v1_dot_service__pb2.V2SpriteRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.V2SpriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageparser.v1.ImageParser/GetScImage',
            imageparser_dot_v1_dot_service__pb2.GetScImageRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.GetScImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
