"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HealthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthRequest: _TypeAlias = HealthRequest  # noqa: Y015

@_typing.final
class HealthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthResponse: _TypeAlias = HealthResponse  # noqa: Y015

@_typing.final
class GetImageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUCKET_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PREFIX_FIELD_NUMBER: _builtins.int
    CACHE_FIELD_NUMBER: _builtins.int
    bucket: _builtins.str
    key: _builtins.str
    prefix: _builtins.str
    cache: _builtins.bool
    def __init__(
        self,
        *,
        bucket: _builtins.str = ...,
        key: _builtins.str = ...,
        prefix: _builtins.str = ...,
        cache: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket", b"bucket", "cache", b"cache", "key", b"key", "prefix", b"prefix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetImageRequest: _TypeAlias = GetImageRequest  # noqa: Y015

@_typing.final
class GetImageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    filename: _builtins.str
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        filename: _builtins.str = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename", "height", b"height", "image_data", b"image_data", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetImageResponse: _TypeAlias = GetImageResponse  # noqa: Y015

@_typing.final
class SpriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUCKET_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PREFIXES_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    CACHE_FIELD_NUMBER: _builtins.int
    bucket: _builtins.str
    key: _builtins.str
    size: _builtins.int
    cache: _builtins.bool
    @_builtins.property
    def prefixes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        bucket: _builtins.str = ...,
        key: _builtins.str = ...,
        prefixes: _abc.Iterable[_builtins.str] | None = ...,
        size: _builtins.int = ...,
        cache: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket", b"bucket", "cache", b"cache", "key", b"key", "prefixes", b"prefixes", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpriteRequest: _TypeAlias = SpriteRequest  # noqa: Y015

@_typing.final
class SpriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "image_data", b"image_data", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpriteResponse: _TypeAlias = SpriteResponse  # noqa: Y015

@_typing.final
class V2SpriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUCKET_FIELD_NUMBER: _builtins.int
    RECORD_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    bucket: _builtins.str
    record: _builtins.str
    size: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        bucket: _builtins.str = ...,
        record: _builtins.str = ...,
        items: _abc.Iterable[_builtins.str] | None = ...,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket", b"bucket", "items", b"items", "record", b"record", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___V2SpriteRequest: _TypeAlias = V2SpriteRequest  # noqa: Y015

@_typing.final
class V2SpriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "image_data", b"image_data", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___V2SpriteResponse: _TypeAlias = V2SpriteResponse  # noqa: Y015

@_typing.final
class GetScImageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    DEFECT_ID_FIELD_NUMBER: _builtins.int
    IMAGE_TYPE_FIELD_NUMBER: _builtins.int
    REVIEW_IMAGE_ID_FIELD_NUMBER: _builtins.int
    inspection_time: _builtins.str
    wafer_key: _builtins.int
    defect_id: _builtins.str
    image_type: _builtins.str
    review_image_id: _builtins.int
    def __init__(
        self,
        *,
        inspection_time: _builtins.str = ...,
        wafer_key: _builtins.int = ...,
        defect_id: _builtins.str = ...,
        image_type: _builtins.str = ...,
        review_image_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["defect_id", b"defect_id", "image_type", b"image_type", "inspection_time", b"inspection_time", "review_image_id", b"review_image_id", "wafer_key", b"wafer_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetScImageRequest: _TypeAlias = GetScImageRequest  # noqa: Y015

@_typing.final
class GetScImageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    content_type: _builtins.str
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        content_type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "image_data", b"image_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetScImageResponse: _TypeAlias = GetScImageResponse  # noqa: Y015

@_typing.final
class ScImageRef(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEFECT_ID_FIELD_NUMBER: _builtins.int
    IMAGE_TYPE_FIELD_NUMBER: _builtins.int
    REVIEW_IMAGE_ID_FIELD_NUMBER: _builtins.int
    defect_id: _builtins.str
    image_type: _builtins.str
    review_image_id: _builtins.int
    def __init__(
        self,
        *,
        defect_id: _builtins.str = ...,
        image_type: _builtins.str = ...,
        review_image_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["defect_id", b"defect_id", "image_type", b"image_type", "review_image_id", b"review_image_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScImageRef: _TypeAlias = ScImageRef  # noqa: Y015

@_typing.final
class BatchGetScImageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    IMAGES_FIELD_NUMBER: _builtins.int
    inspection_time: _builtins.str
    wafer_key: _builtins.int
    @_builtins.property
    def images(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScImageRef]: ...
    def __init__(
        self,
        *,
        inspection_time: _builtins.str = ...,
        wafer_key: _builtins.int = ...,
        images: _abc.Iterable[Global___ScImageRef] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["images", b"images", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BatchGetScImageRequest: _TypeAlias = BatchGetScImageRequest  # noqa: Y015

@_typing.final
class ScImageResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEFECT_ID_FIELD_NUMBER: _builtins.int
    IMAGE_TYPE_FIELD_NUMBER: _builtins.int
    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    defect_id: _builtins.str
    image_type: _builtins.str
    image_data: _builtins.bytes
    content_type: _builtins.str
    error: _builtins.str
    def __init__(
        self,
        *,
        defect_id: _builtins.str = ...,
        image_type: _builtins.str = ...,
        image_data: _builtins.bytes = ...,
        content_type: _builtins.str = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "defect_id", b"defect_id", "error", b"error", "image_data", b"image_data", "image_type", b"image_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScImageResult: _TypeAlias = ScImageResult  # noqa: Y015

@_typing.final
class BatchGetScImageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScImageResult]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___ScImageResult] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BatchGetScImageResponse: _TypeAlias = BatchGetScImageResponse  # noqa: Y015

@_typing.final
class StreamScInspectionImagesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    DEFECT_IDS_FIELD_NUMBER: _builtins.int
    IMAGE_TYPES_FIELD_NUMBER: _builtins.int
    inspection_time: _builtins.str
    wafer_key: _builtins.int
    @_builtins.property
    def defect_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def image_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        inspection_time: _builtins.str = ...,
        wafer_key: _builtins.int = ...,
        defect_ids: _abc.Iterable[_builtins.int] | None = ...,
        image_types: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["defect_ids", b"defect_ids", "image_types", b"image_types", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamScInspectionImagesRequest: _TypeAlias = StreamScInspectionImagesRequest  # noqa: Y015

@_typing.final
class ResolvePatchImagesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FORMAT_FIELD_NUMBER: _builtins.int
    ROLES_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    source_format: _builtins.str
    """Format identifies the code-registered filesystem driver. It is not a
    deployment profile and never carries a root path or credentials.
    """
    @_builtins.property
    def roles(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResolvePatchImageItem]: ...
    def __init__(
        self,
        *,
        source_format: _builtins.str = ...,
        roles: _abc.Iterable[_builtins.str] | None = ...,
        items: _abc.Iterable[Global___ResolvePatchImageItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "roles", b"roles", "source_format", b"source_format"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolvePatchImagesRequest: _TypeAlias = ResolvePatchImagesRequest  # noqa: Y015

@_typing.final
class ResolvePatchImageItem(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class RolePathsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    SAMPLE_ID_FIELD_NUMBER: _builtins.int
    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    DEFECT_ID_FIELD_NUMBER: _builtins.int
    ROLE_PATHS_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    sample_id: _builtins.str
    inspection_time: _builtins.str
    wafer_key: _builtins.int
    defect_id: _builtins.str
    @_builtins.property
    def role_paths(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Direct-file drivers consume explicit role-relative paths. Layout-based
        compatibility drivers ignore this field and derive their own addresses.
        """

    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        sample_id: _builtins.str = ...,
        inspection_time: _builtins.str = ...,
        wafer_key: _builtins.int = ...,
        defect_id: _builtins.str = ...,
        role_paths: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["defect_id", b"defect_id", "inspection_time", b"inspection_time", "request_id", b"request_id", "role_paths", b"role_paths", "sample_id", b"sample_id", "wafer_key", b"wafer_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolvePatchImageItem: _TypeAlias = ResolvePatchImageItem  # noqa: Y015

@_typing.final
class ResolvePatchImageResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    SAMPLE_ID_FIELD_NUMBER: _builtins.int
    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    DEFECT_ID_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    sample_id: _builtins.str
    inspection_time: _builtins.str
    wafer_key: _builtins.int
    defect_id: _builtins.str
    role: _builtins.str
    image_data: _builtins.bytes
    content_type: _builtins.str
    error: _builtins.str
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        sample_id: _builtins.str = ...,
        inspection_time: _builtins.str = ...,
        wafer_key: _builtins.int = ...,
        defect_id: _builtins.str = ...,
        role: _builtins.str = ...,
        image_data: _builtins.bytes = ...,
        content_type: _builtins.str = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "defect_id", b"defect_id", "error", b"error", "image_data", b"image_data", "inspection_time", b"inspection_time", "request_id", b"request_id", "role", b"role", "sample_id", b"sample_id", "wafer_key", b"wafer_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolvePatchImageResult: _TypeAlias = ResolvePatchImageResult  # noqa: Y015

@_typing.final
class ResolvePatchImagesBatchResponse(_message.Message):
    """One ordered response frame used by stdin/stdout resolver processes. It is
    deliberately not an RPC response: training, batch prediction, and pure-local
    instant prediction never consume the display ImageParser service.
    """

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResolvePatchImageResult]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___ResolvePatchImageResult] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResolvePatchImagesBatchResponse: _TypeAlias = ResolvePatchImagesBatchResponse  # noqa: Y015

@_typing.final
class WarmScCacheRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    DEFECT_IDS_FIELD_NUMBER: _builtins.int
    inspection_time: _builtins.str
    wafer_key: _builtins.int
    @_builtins.property
    def defect_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        inspection_time: _builtins.str = ...,
        wafer_key: _builtins.int = ...,
        defect_ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["defect_ids", b"defect_ids", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WarmScCacheRequest: _TypeAlias = WarmScCacheRequest  # noqa: Y015

@_typing.final
class WarmScCacheResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    ZIPS_WARMED_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    zips_warmed: _builtins.int
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
        zips_warmed: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "zips_warmed", b"zips_warmed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WarmScCacheResponse: _TypeAlias = WarmScCacheResponse  # noqa: Y015
