# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_stubs.imageparser.v1 import service_pb2 as imageparser_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in imageparser/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/imageparser.v1.ImageParser/Health',
                request_serializer=imageparser_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetImage = channel.unary_unary(
                '/imageparser.v1.ImageParser/GetImage',
                request_serializer=imageparser_dot_v1_dot_service__pb2.GetImageRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.GetImageResponse.FromString,
                _registered_method=True)
        self.Sprite = channel.unary_unary(
                '/imageparser.v1.ImageParser/Sprite',
                request_serializer=imageparser_dot_v1_dot_service__pb2.SpriteRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.SpriteResponse.FromString,
                _registered_method=True)
        self.V2Sprite = channel.unary_unary(
                '/imageparser.v1.ImageParser/V2Sprite',
                request_serializer=imageparser_dot_v1_dot_service__pb2.V2SpriteRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.V2SpriteResponse.FromString,
                _registered_method=True)
        self.GetScImage = channel.unary_unary(
                '/imageparser.v1.ImageParser/GetScImage',
                request_serializer=imageparser_dot_v1_dot_service__pb2.GetScImageRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.GetScImageResponse.FromString,
                _registered_method=True)
        self.BatchGetScImage = channel.unary_unary(
                '/imageparser.v1.ImageParser/BatchGetScImage',
                request_serializer=imageparser_dot_v1_dot_service__pb2.BatchGetScImageRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.BatchGetScImageResponse.FromString,
                _registered_method=True)
        self.StreamScInspectionImages = channel.unary_stream(
                '/imageparser.v1.ImageParser/StreamScInspectionImages',
                request_serializer=imageparser_dot_v1_dot_service__pb2.StreamScInspectionImagesRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.ScImageResult.FromString,
                _registered_method=True)
        self.WarmScCache = channel.unary_unary(
                '/imageparser.v1.ImageParser/WarmScCache',
                request_serializer=imageparser_dot_v1_dot_service__pb2.WarmScCacheRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.WarmScCacheResponse.FromString,
                _registered_method=True)


class ImageParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sprite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def V2Sprite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetScImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScInspectionImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WarmScCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.HealthRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.HealthResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.GetImageRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.GetImageResponse.SerializeToString,
            ),
            'Sprite': grpc.unary_unary_rpc_method_handler(
                    servicer.Sprite,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.SpriteRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.SpriteResponse.SerializeToString,
            ),
            'V2Sprite': grpc.unary_unary_rpc_method_handler(
                    servicer.V2Sprite,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.V2SpriteRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.V2SpriteResponse.SerializeToString,
            ),
            'GetScImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScImage,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.GetScImageRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.GetScImageResponse.SerializeToString,
            ),
            'BatchGetScImage': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetScImage,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.BatchGetScImageRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.BatchGetScImageResponse.SerializeToString,
            ),
            'StreamScInspectionImages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScInspectionImages,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.StreamScInspectionImagesRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.ScImageResult.SerializeToString,
            ),
            'WarmScCache': grpc.unary_unary_rpc_method_handler(
                    servicer.WarmScCache,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.WarmScCacheRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.WarmScCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageparser.v1.ImageParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageparser.v1.ImageParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/Health',
            imageparser_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/GetImage',
            imageparser_dot_v1_dot_service__pb2.GetImageRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.GetImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sprite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/Sprite',
            imageparser_dot_v1_dot_service__pb2.SpriteRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.SpriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def V2Sprite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/V2Sprite',
            imageparser_dot_v1_dot_service__pb2.V2SpriteRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.V2SpriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/GetScImage',
            imageparser_dot_v1_dot_service__pb2.GetScImageRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.GetScImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetScImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/BatchGetScImage',
            imageparser_dot_v1_dot_service__pb2.BatchGetScImageRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.BatchGetScImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScInspectionImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/imageparser.v1.ImageParser/StreamScInspectionImages',
            imageparser_dot_v1_dot_service__pb2.StreamScInspectionImagesRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.ScImageResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WarmScCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/WarmScCache',
            imageparser_dot_v1_dot_service__pb2.WarmScCacheRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.WarmScCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
