# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_stubs.imageparser.v1 import service_pb2 as imageparser_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in imageparser/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/imageparser.v1.ImageParser/Health',
                request_serializer=imageparser_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamPredictionImages = channel.stream_stream(
                '/imageparser.v1.ImageParser/StreamPredictionImages',
                request_serializer=imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.FromString,
                _registered_method=True)
        self.StreamTrainingImages = channel.stream_stream(
                '/imageparser.v1.ImageParser/StreamTrainingImages',
                request_serializer=imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.FromString,
                _registered_method=True)
        self.StreamExportImages = channel.stream_stream(
                '/imageparser.v1.ImageParser/StreamExportImages',
                request_serializer=imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.SerializeToString,
                response_deserializer=imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.FromString,
                _registered_method=True)


class ImageParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredictionImages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrainingImages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExportImages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.HealthRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.HealthResponse.SerializeToString,
            ),
            'StreamPredictionImages': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredictionImages,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.SerializeToString,
            ),
            'StreamTrainingImages': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTrainingImages,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.SerializeToString,
            ),
            'StreamExportImages': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExportImages,
                    request_deserializer=imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.FromString,
                    response_serializer=imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageparser.v1.ImageParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageparser.v1.ImageParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imageparser.v1.ImageParser/Health',
            imageparser_dot_v1_dot_service__pb2.HealthRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredictionImages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imageparser.v1.ImageParser/StreamPredictionImages',
            imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrainingImages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imageparser.v1.ImageParser/StreamTrainingImages',
            imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExportImages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imageparser.v1.ImageParser/StreamExportImages',
            imageparser_dot_v1_dot_service__pb2.StreamImagesRequest.SerializeToString,
            imageparser_dot_v1_dot_service__pb2.StreamImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
