"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReviewImage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_NAME_FIELD_NUMBER: _builtins.int
    IMAGE_ID_FIELD_NUMBER: _builtins.int
    IMAGE_TYPE_FIELD_NUMBER: _builtins.int
    image_name: _builtins.str
    image_id: _builtins.int
    image_type: _builtins.str
    def __init__(
        self,
        *,
        image_name: _builtins.str = ...,
        image_id: _builtins.int = ...,
        image_type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["image_id", b"image_id", "image_name", b"image_name", "image_type", b"image_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReviewImage: _TypeAlias = ReviewImage  # noqa: Y015

@_typing.final
class ScSampleItem(_message.Message):
    """# 定义正确"""

    DESCRIPTOR: _descriptor.Descriptor

    DEFECT_ID_FIELD_NUMBER: _builtins.int
    WAFER_X_FIELD_NUMBER: _builtins.int
    WAFER_Y_FIELD_NUMBER: _builtins.int
    ROUGH_BIN_FIELD_NUMBER: _builtins.int
    CLASS_NUMBER_FIELD_NUMBER: _builtins.int
    REVIEW_IMAGES_FIELD_NUMBER: _builtins.int
    INSPECTION_TIME_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    INDEX_X_FIELD_NUMBER: _builtins.int
    INDEX_Y_FIELD_NUMBER: _builtins.int
    ADDER_FIELD_NUMBER: _builtins.int
    CLUSTER_FIELD_NUMBER: _builtins.int
    TEST_ID_FIELD_NUMBER: _builtins.int
    defect_id: _builtins.int
    wafer_x: _builtins.int
    wafer_y: _builtins.int
    rough_bin: _builtins.int
    class_number: _builtins.int
    inspection_time: _builtins.int
    wafer_key: _builtins.int
    index_x: _builtins.int
    index_y: _builtins.int
    adder: _builtins.int
    cluster: _builtins.int
    test_id: _builtins.int
    @_builtins.property
    def review_images(self) -> _containers.RepeatedCompositeFieldContainer[Global___ReviewImage]: ...
    def __init__(
        self,
        *,
        defect_id: _builtins.int = ...,
        wafer_x: _builtins.int = ...,
        wafer_y: _builtins.int = ...,
        rough_bin: _builtins.int = ...,
        class_number: _builtins.int | None = ...,
        review_images: _abc.Iterable[Global___ReviewImage] | None = ...,
        inspection_time: _builtins.int = ...,
        wafer_key: _builtins.int = ...,
        index_x: _builtins.int = ...,
        index_y: _builtins.int = ...,
        adder: _builtins.int = ...,
        cluster: _builtins.int = ...,
        test_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_class_number", b"_class_number", "class_number", b"class_number"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_class_number", b"_class_number", "adder", b"adder", "class_number", b"class_number", "cluster", b"cluster", "defect_id", b"defect_id", "index_x", b"index_x", "index_y", b"index_y", "inspection_time", b"inspection_time", "review_images", b"review_images", "rough_bin", b"rough_bin", "test_id", b"test_id", "wafer_key", b"wafer_key", "wafer_x", b"wafer_x", "wafer_y", b"wafer_y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__class_number: _TypeAlias = _typing.Literal["class_number"]  # noqa: Y015
    _WhichOneofArgType__class_number: _TypeAlias = _typing.Literal["_class_number", b"_class_number"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__class_number) -> _WhichOneofReturnType__class_number | None: ...

Global___ScSampleItem: _TypeAlias = ScSampleItem  # noqa: Y015

@_typing.final
class WaferGeometry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WAFER_RADIUS_NM_FIELD_NUMBER: _builtins.int
    CENTER_X_FIELD_NUMBER: _builtins.int
    CENTER_Y_FIELD_NUMBER: _builtins.int
    ORIGIN_X_FIELD_NUMBER: _builtins.int
    ORIGIN_Y_FIELD_NUMBER: _builtins.int
    DIE_SIZE_X_FIELD_NUMBER: _builtins.int
    DIE_SIZE_Y_FIELD_NUMBER: _builtins.int
    wafer_radius_nm: _builtins.int
    center_x: _builtins.int
    center_y: _builtins.int
    origin_x: _builtins.int
    origin_y: _builtins.int
    die_size_x: _builtins.int
    die_size_y: _builtins.int
    def __init__(
        self,
        *,
        wafer_radius_nm: _builtins.int = ...,
        center_x: _builtins.int = ...,
        center_y: _builtins.int = ...,
        origin_x: _builtins.int = ...,
        origin_y: _builtins.int = ...,
        die_size_x: _builtins.int = ...,
        die_size_y: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center_x", b"center_x", "center_y", b"center_y", "die_size_x", b"die_size_x", "die_size_y", b"die_size_y", "origin_x", b"origin_x", "origin_y", b"origin_y", "wafer_radius_nm", b"wafer_radius_nm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WaferGeometry: _TypeAlias = WaferGeometry  # noqa: Y015

@_typing.final
class WaferMapResponse(_message.Message):
    """WaferMapResponse is the unified aggregated response for Preview mode
    (inspection upstream) and Dataset View mode (dataset store).
    Returns all three map datasets in a single response:
      - Wafer map points (wafer coordinates)
      - Die stack map points (die-relative coordinates)
      - Reticle map points (reticle-frame coordinates)

    Each per-point array packs 6 int32 values:
      [x, y, defect_id, class_number, rough_bin, has_review, x, y, ...]
    where has_review is 0 or 1.

    Endpoints:
      GET /sc/inspections/{time}/{wafer_key}/map-data   (Preview)
      GET /sc/datasets/{dataset_id}/map-data             (Dataset View)
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class LegendGroupsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___DefectList: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___DefectList | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TOTAL_FIELD_NUMBER: _builtins.int
    WAFER_KEY_FIELD_NUMBER: _builtins.int
    GEOMETRY_FIELD_NUMBER: _builtins.int
    WAFER_POINTS_FIELD_NUMBER: _builtins.int
    DIE_POINTS_FIELD_NUMBER: _builtins.int
    RETICLE_POINTS_FIELD_NUMBER: _builtins.int
    RETICLE_X_DIE_COUNT_FIELD_NUMBER: _builtins.int
    RETICLE_Y_DIE_COUNT_FIELD_NUMBER: _builtins.int
    IS_SAMPLED_FIELD_NUMBER: _builtins.int
    LEGEND_GROUP_BY_FIELD_NUMBER: _builtins.int
    LEGEND_GROUPS_FIELD_NUMBER: _builtins.int
    total: _builtins.int
    wafer_key: _builtins.int
    reticle_x_die_count: _builtins.int
    """Reticle grid configuration — number of dies grouped into each reticle frame"""
    reticle_y_die_count: _builtins.int
    is_sampled: _builtins.bool
    """True when point arrays contain grid-downsampled data (total still reports full count)"""
    legend_group_by: _builtins.str
    """Active grouping dimension for frontend legend rendering.
    Empty string means default grouping (class_number).
    """
    @_builtins.property
    def geometry(self) -> Global___WaferGeometry: ...
    @_builtins.property
    def wafer_points(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """6 ints per point: wafer_x, wafer_y, defect_id, class_number, rough_bin, has_review_image"""

    @_builtins.property
    def die_points(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """6 ints per point: die_x, die_y, defect_id, class_number, rough_bin, has_review_image"""

    @_builtins.property
    def reticle_points(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """6 ints per point: reticle_x, reticle_y, defect_id, class_number, rough_bin, has_review_image"""

    @_builtins.property
    def legend_groups(self) -> _containers.MessageMap[_builtins.str, Global___DefectList]:
        """Defect ID groups for the active legend dimension.
        Key is the group name (e.g. "3" for class_number 3, "__unlabeled__" for missing labels).
        """

    def __init__(
        self,
        *,
        total: _builtins.int = ...,
        wafer_key: _builtins.int = ...,
        geometry: Global___WaferGeometry | None = ...,
        wafer_points: _abc.Iterable[_builtins.int] | None = ...,
        die_points: _abc.Iterable[_builtins.int] | None = ...,
        reticle_points: _abc.Iterable[_builtins.int] | None = ...,
        reticle_x_die_count: _builtins.int = ...,
        reticle_y_die_count: _builtins.int = ...,
        is_sampled: _builtins.bool = ...,
        legend_group_by: _builtins.str = ...,
        legend_groups: _abc.Mapping[_builtins.str, Global___DefectList] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["geometry", b"geometry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["die_points", b"die_points", "geometry", b"geometry", "is_sampled", b"is_sampled", "legend_group_by", b"legend_group_by", "legend_groups", b"legend_groups", "reticle_points", b"reticle_points", "reticle_x_die_count", b"reticle_x_die_count", "reticle_y_die_count", b"reticle_y_die_count", "total", b"total", "wafer_key", b"wafer_key", "wafer_points", b"wafer_points"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WaferMapResponse: _TypeAlias = WaferMapResponse  # noqa: Y015

@_typing.final
class DefectList(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    DEFECT_IDS_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    @_builtins.property
    def defect_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
        defect_ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "defect_ids", b"defect_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DefectList: _TypeAlias = DefectList  # noqa: Y015
