"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ReviewImage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_NAME_FIELD_NUMBER: builtins.int
    IMAGE_ID_FIELD_NUMBER: builtins.int
    IMAGE_TYPE_FIELD_NUMBER: builtins.int
    image_name: builtins.str
    image_id: builtins.int
    image_type: builtins.str
    def __init__(
        self,
        *,
        image_name: builtins.str = ...,
        image_id: builtins.int = ...,
        image_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["image_id", b"image_id", "image_name", b"image_name", "image_type", b"image_type"]) -> None: ...

global___ReviewImage = ReviewImage

@typing.final
class ScSampleItem(google.protobuf.message.Message):
    """# 定义正确"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFECT_ID_FIELD_NUMBER: builtins.int
    WAFER_X_FIELD_NUMBER: builtins.int
    WAFER_Y_FIELD_NUMBER: builtins.int
    ROUGH_BIN_FIELD_NUMBER: builtins.int
    CLASS_NUMBER_FIELD_NUMBER: builtins.int
    REVIEW_IMAGES_FIELD_NUMBER: builtins.int
    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    INDEX_X_FIELD_NUMBER: builtins.int
    INDEX_Y_FIELD_NUMBER: builtins.int
    ADDER_FIELD_NUMBER: builtins.int
    CLUSTER_FIELD_NUMBER: builtins.int
    TEST_ID_FIELD_NUMBER: builtins.int
    defect_id: builtins.int
    wafer_x: builtins.int
    wafer_y: builtins.int
    rough_bin: builtins.int
    class_number: builtins.int
    inspection_time: builtins.int
    wafer_key: builtins.int
    index_x: builtins.int
    index_y: builtins.int
    adder: builtins.int
    cluster: builtins.int
    test_id: builtins.int
    @property
    def review_images(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReviewImage]: ...
    def __init__(
        self,
        *,
        defect_id: builtins.int = ...,
        wafer_x: builtins.int = ...,
        wafer_y: builtins.int = ...,
        rough_bin: builtins.int = ...,
        class_number: builtins.int | None = ...,
        review_images: collections.abc.Iterable[global___ReviewImage] | None = ...,
        inspection_time: builtins.int = ...,
        wafer_key: builtins.int = ...,
        index_x: builtins.int = ...,
        index_y: builtins.int = ...,
        adder: builtins.int = ...,
        cluster: builtins.int = ...,
        test_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_class_number", b"_class_number", "class_number", b"class_number"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_class_number", b"_class_number", "adder", b"adder", "class_number", b"class_number", "cluster", b"cluster", "defect_id", b"defect_id", "index_x", b"index_x", "index_y", b"index_y", "inspection_time", b"inspection_time", "review_images", b"review_images", "rough_bin", b"rough_bin", "test_id", b"test_id", "wafer_key", b"wafer_key", "wafer_x", b"wafer_x", "wafer_y", b"wafer_y"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_class_number", b"_class_number"]) -> typing.Literal["class_number"] | None: ...

global___ScSampleItem = ScSampleItem

@typing.final
class WaferGeometry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WAFER_RADIUS_NM_FIELD_NUMBER: builtins.int
    CENTER_X_FIELD_NUMBER: builtins.int
    CENTER_Y_FIELD_NUMBER: builtins.int
    ORIGIN_X_FIELD_NUMBER: builtins.int
    ORIGIN_Y_FIELD_NUMBER: builtins.int
    DIE_SIZE_X_FIELD_NUMBER: builtins.int
    DIE_SIZE_Y_FIELD_NUMBER: builtins.int
    wafer_radius_nm: builtins.int
    center_x: builtins.int
    center_y: builtins.int
    origin_x: builtins.int
    origin_y: builtins.int
    die_size_x: builtins.int
    die_size_y: builtins.int
    def __init__(
        self,
        *,
        wafer_radius_nm: builtins.int = ...,
        center_x: builtins.int = ...,
        center_y: builtins.int = ...,
        origin_x: builtins.int = ...,
        origin_y: builtins.int = ...,
        die_size_x: builtins.int = ...,
        die_size_y: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["center_x", b"center_x", "center_y", b"center_y", "die_size_x", b"die_size_x", "die_size_y", b"die_size_y", "origin_x", b"origin_x", "origin_y", b"origin_y", "wafer_radius_nm", b"wafer_radius_nm"]) -> None: ...

global___WaferGeometry = WaferGeometry

@typing.final
class WaferMapResponse(google.protobuf.message.Message):
    """WaferMapResponse is the unified aggregated response for Preview mode
    (inspection upstream) and Dataset View mode (dataset store).
    Returns all three map datasets in a single response:
      - Wafer map points (wafer coordinates)
      - Die stack map points (die-relative coordinates)
      - Reticle map points (reticle-frame coordinates)

    Each per-point array packs 6 int32 values:
      [x, y, defect_id, class_number, rough_bin, has_review, x, y, ...]
    where has_review is 0 or 1.

    Endpoints:
      GET /sc/inspections/{time}/{wafer_key}/map-data   (Preview)
      GET /sc/datasets/{dataset_id}/map-data             (Dataset View)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LegendGroupsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___DefectList: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___DefectList | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    TOTAL_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    GEOMETRY_FIELD_NUMBER: builtins.int
    WAFER_POINTS_FIELD_NUMBER: builtins.int
    DIE_POINTS_FIELD_NUMBER: builtins.int
    RETICLE_POINTS_FIELD_NUMBER: builtins.int
    RETICLE_X_DIE_COUNT_FIELD_NUMBER: builtins.int
    RETICLE_Y_DIE_COUNT_FIELD_NUMBER: builtins.int
    IS_SAMPLED_FIELD_NUMBER: builtins.int
    LEGEND_GROUP_BY_FIELD_NUMBER: builtins.int
    LEGEND_GROUPS_FIELD_NUMBER: builtins.int
    total: builtins.int
    wafer_key: builtins.int
    reticle_x_die_count: builtins.int
    """Reticle grid configuration — number of dies grouped into each reticle frame"""
    reticle_y_die_count: builtins.int
    is_sampled: builtins.bool
    """True when point arrays contain grid-downsampled data (total still reports full count)"""
    legend_group_by: builtins.str
    """Active grouping dimension for frontend legend rendering.
    Empty string means default grouping (class_number).
    """
    @property
    def geometry(self) -> global___WaferGeometry: ...
    @property
    def wafer_points(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """6 ints per point: wafer_x, wafer_y, defect_id, class_number, rough_bin, has_review_image"""

    @property
    def die_points(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """6 ints per point: die_x, die_y, defect_id, class_number, rough_bin, has_review_image"""

    @property
    def reticle_points(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """6 ints per point: reticle_x, reticle_y, defect_id, class_number, rough_bin, has_review_image"""

    @property
    def legend_groups(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___DefectList]:
        """Defect ID groups for the active legend dimension.
        Key is the group name (e.g. "3" for class_number 3, "__unlabeled__" for missing labels).
        """

    def __init__(
        self,
        *,
        total: builtins.int = ...,
        wafer_key: builtins.int = ...,
        geometry: global___WaferGeometry | None = ...,
        wafer_points: collections.abc.Iterable[builtins.int] | None = ...,
        die_points: collections.abc.Iterable[builtins.int] | None = ...,
        reticle_points: collections.abc.Iterable[builtins.int] | None = ...,
        reticle_x_die_count: builtins.int = ...,
        reticle_y_die_count: builtins.int = ...,
        is_sampled: builtins.bool = ...,
        legend_group_by: builtins.str = ...,
        legend_groups: collections.abc.Mapping[builtins.str, global___DefectList] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["geometry", b"geometry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["die_points", b"die_points", "geometry", b"geometry", "is_sampled", b"is_sampled", "legend_group_by", b"legend_group_by", "legend_groups", b"legend_groups", "reticle_points", b"reticle_points", "reticle_x_die_count", b"reticle_x_die_count", "reticle_y_die_count", b"reticle_y_die_count", "total", b"total", "wafer_key", b"wafer_key", "wafer_points", b"wafer_points"]) -> None: ...

global___WaferMapResponse = WaferMapResponse

@typing.final
class DefectList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COUNT_FIELD_NUMBER: builtins.int
    DEFECT_IDS_FIELD_NUMBER: builtins.int
    count: builtins.int
    @property
    def defect_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        count: builtins.int = ...,
        defect_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["count", b"count", "defect_ids", b"defect_ids"]) -> None: ...

global___DefectList = DefectList
