"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HealthRequest = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___HealthResponse = HealthResponse

@typing.final
class GetInspectionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]) -> None: ...

global___GetInspectionRequest = GetInspectionRequest

@typing.final
class GetInspectionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    LOT_ID_FIELD_NUMBER: builtins.int
    WAFER_ID_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    LAYER_ID_FIELD_NUMBER: builtins.int
    CENTER_X_FIELD_NUMBER: builtins.int
    CENTER_Y_FIELD_NUMBER: builtins.int
    ORIGIN_X_FIELD_NUMBER: builtins.int
    ORIGIN_Y_FIELD_NUMBER: builtins.int
    DIE_SIZE_X_FIELD_NUMBER: builtins.int
    DIE_SIZE_Y_FIELD_NUMBER: builtins.int
    EQP_ID_FIELD_NUMBER: builtins.int
    RECIPE_ID_FIELD_NUMBER: builtins.int
    DEFECTS_FIELD_NUMBER: builtins.int
    IMAGES_FIELD_NUMBER: builtins.int
    ORIGIN_INDEX_X_FIELD_NUMBER: builtins.int
    ORIGIN_INDEX_Y_FIELD_NUMBER: builtins.int
    LATEST_UPDATE_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    lot_id: builtins.str
    wafer_id: builtins.str
    device: builtins.str
    layer_id: builtins.str
    center_x: builtins.int
    center_y: builtins.int
    origin_x: builtins.int
    origin_y: builtins.int
    die_size_x: builtins.int
    die_size_y: builtins.int
    eqp_id: builtins.str
    recipe_id: builtins.str
    defects: builtins.int
    images: builtins.int
    origin_index_x: builtins.int
    origin_index_y: builtins.int
    latest_update: builtins.int
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        lot_id: builtins.str = ...,
        wafer_id: builtins.str = ...,
        device: builtins.str = ...,
        layer_id: builtins.str = ...,
        center_x: builtins.int = ...,
        center_y: builtins.int = ...,
        origin_x: builtins.int = ...,
        origin_y: builtins.int = ...,
        die_size_x: builtins.int = ...,
        die_size_y: builtins.int = ...,
        eqp_id: builtins.str = ...,
        recipe_id: builtins.str = ...,
        defects: builtins.int = ...,
        images: builtins.int = ...,
        origin_index_x: builtins.int = ...,
        origin_index_y: builtins.int = ...,
        latest_update: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["center_x", b"center_x", "center_y", b"center_y", "defects", b"defects", "device", b"device", "die_size_x", b"die_size_x", "die_size_y", b"die_size_y", "eqp_id", b"eqp_id", "images", b"images", "inspection_time", b"inspection_time", "latest_update", b"latest_update", "layer_id", b"layer_id", "lot_id", b"lot_id", "origin_index_x", b"origin_index_x", "origin_index_y", b"origin_index_y", "origin_x", b"origin_x", "origin_y", b"origin_y", "recipe_id", b"recipe_id", "wafer_id", b"wafer_id", "wafer_key", b"wafer_key"]) -> None: ...

global___GetInspectionResponse = GetInspectionResponse

@typing.final
class GetInspectionPatchZipsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    LOT_ID_FIELD_NUMBER: builtins.int
    WAFER_ID_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    LAYER_ID_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    lot_id: builtins.str
    wafer_id: builtins.str
    device: builtins.str
    layer_id: builtins.str
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        lot_id: builtins.str = ...,
        wafer_id: builtins.str = ...,
        device: builtins.str = ...,
        layer_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["device", b"device", "inspection_time", b"inspection_time", "layer_id", b"layer_id", "lot_id", b"lot_id", "wafer_id", b"wafer_id"]) -> None: ...

global___GetInspectionPatchZipsRequest = GetInspectionPatchZipsRequest

@typing.final
class ZipRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    S3_BUCKET_FIELD_NUMBER: builtins.int
    S3_KEY_FIELD_NUMBER: builtins.int
    s3_bucket: builtins.str
    s3_key: builtins.str
    def __init__(
        self,
        *,
        s3_bucket: builtins.str = ...,
        s3_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["s3_bucket", b"s3_bucket", "s3_key", b"s3_key"]) -> None: ...

global___ZipRef = ZipRef

@typing.final
class GetInspectionPatchZipsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZIPS_FIELD_NUMBER: builtins.int
    @property
    def zips(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ZipRef]: ...
    def __init__(
        self,
        *,
        zips: collections.abc.Iterable[global___ZipRef] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["zips", b"zips"]) -> None: ...

global___GetInspectionPatchZipsResponse = GetInspectionPatchZipsResponse

@typing.final
class GetReviewImageFileSpecRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    DEFECT_ID_FIELD_NUMBER: builtins.int
    IMAGE_ID_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    defect_id: builtins.int
    image_id: builtins.int
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        defect_id: builtins.int = ...,
        image_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defect_id", b"defect_id", "image_id", b"image_id", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]) -> None: ...

global___GetReviewImageFileSpecRequest = GetReviewImageFileSpecRequest

@typing.final
class GetReviewImageFileSpecResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FILESPEC_FIELD_NUMBER: builtins.int
    image_filespec: builtins.str
    def __init__(
        self,
        *,
        image_filespec: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["image_filespec", b"image_filespec"]) -> None: ...

global___GetReviewImageFileSpecResponse = GetReviewImageFileSpecResponse

@typing.final
class ListReviewImagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    DEFECT_ID_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    defect_id: builtins.int
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        defect_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defect_id", b"defect_id", "inspection_time", b"inspection_time", "wafer_key", b"wafer_key"]) -> None: ...

global___ListReviewImagesRequest = ListReviewImagesRequest

@typing.final
class ReviewImageRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FILESPEC_FIELD_NUMBER: builtins.int
    DEFECT_ID_FIELD_NUMBER: builtins.int
    IMAGE_ID_FIELD_NUMBER: builtins.int
    IMAGE_TYPE_FIELD_NUMBER: builtins.int
    image_filespec: builtins.str
    defect_id: builtins.int
    image_id: builtins.int
    image_type: builtins.str
    def __init__(
        self,
        *,
        image_filespec: builtins.str = ...,
        defect_id: builtins.int = ...,
        image_id: builtins.int = ...,
        image_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["defect_id", b"defect_id", "image_filespec", b"image_filespec", "image_id", b"image_id", "image_type", b"image_type"]) -> None: ...

global___ReviewImageRef = ReviewImageRef

@typing.final
class ListReviewImagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGES_FIELD_NUMBER: builtins.int
    @property
    def images(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReviewImageRef]: ...
    def __init__(
        self,
        *,
        images: collections.abc.Iterable[global___ReviewImageRef] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["images", b"images"]) -> None: ...

global___ListReviewImagesResponse = ListReviewImagesResponse

@typing.final
class ListInspectionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    LOT_ID_FIELD_NUMBER: builtins.int
    WAFER_ID_FIELD_NUMBER: builtins.int
    LAYER_ID_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    start_time: builtins.str
    end_time: builtins.str
    lot_id: builtins.str
    wafer_id: builtins.str
    layer_id: builtins.str
    device: builtins.str
    def __init__(
        self,
        *,
        start_time: builtins.str = ...,
        end_time: builtins.str = ...,
        lot_id: builtins.str = ...,
        wafer_id: builtins.str = ...,
        layer_id: builtins.str = ...,
        device: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["device", b"device", "end_time", b"end_time", "layer_id", b"layer_id", "lot_id", b"lot_id", "start_time", b"start_time", "wafer_id", b"wafer_id"]) -> None: ...

global___ListInspectionsRequest = ListInspectionsRequest

@typing.final
class InspectionSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSPECTION_TIME_FIELD_NUMBER: builtins.int
    WAFER_KEY_FIELD_NUMBER: builtins.int
    LOT_ID_FIELD_NUMBER: builtins.int
    WAFER_ID_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    LAYER_ID_FIELD_NUMBER: builtins.int
    EQP_ID_FIELD_NUMBER: builtins.int
    RECIPE_ID_FIELD_NUMBER: builtins.int
    DEFECTS_FIELD_NUMBER: builtins.int
    IMAGES_FIELD_NUMBER: builtins.int
    CENTER_X_FIELD_NUMBER: builtins.int
    CENTER_Y_FIELD_NUMBER: builtins.int
    ORIGIN_X_FIELD_NUMBER: builtins.int
    ORIGIN_Y_FIELD_NUMBER: builtins.int
    DIE_SIZE_X_FIELD_NUMBER: builtins.int
    DIE_SIZE_Y_FIELD_NUMBER: builtins.int
    ORIGIN_INDEX_X_FIELD_NUMBER: builtins.int
    ORIGIN_INDEX_Y_FIELD_NUMBER: builtins.int
    inspection_time: builtins.str
    wafer_key: builtins.int
    lot_id: builtins.str
    wafer_id: builtins.str
    device: builtins.str
    layer_id: builtins.str
    eqp_id: builtins.str
    recipe_id: builtins.str
    defects: builtins.int
    images: builtins.int
    center_x: builtins.int
    center_y: builtins.int
    origin_x: builtins.int
    origin_y: builtins.int
    die_size_x: builtins.int
    die_size_y: builtins.int
    origin_index_x: builtins.int
    origin_index_y: builtins.int
    def __init__(
        self,
        *,
        inspection_time: builtins.str = ...,
        wafer_key: builtins.int = ...,
        lot_id: builtins.str = ...,
        wafer_id: builtins.str = ...,
        device: builtins.str = ...,
        layer_id: builtins.str = ...,
        eqp_id: builtins.str = ...,
        recipe_id: builtins.str = ...,
        defects: builtins.int = ...,
        images: builtins.int = ...,
        center_x: builtins.int = ...,
        center_y: builtins.int = ...,
        origin_x: builtins.int = ...,
        origin_y: builtins.int = ...,
        die_size_x: builtins.int = ...,
        die_size_y: builtins.int = ...,
        origin_index_x: builtins.int = ...,
        origin_index_y: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["center_x", b"center_x", "center_y", b"center_y", "defects", b"defects", "device", b"device", "die_size_x", b"die_size_x", "die_size_y", b"die_size_y", "eqp_id", b"eqp_id", "images", b"images", "inspection_time", b"inspection_time", "layer_id", b"layer_id", "lot_id", b"lot_id", "origin_index_x", b"origin_index_x", "origin_index_y", b"origin_index_y", "origin_x", b"origin_x", "origin_y", b"origin_y", "recipe_id", b"recipe_id", "wafer_id", b"wafer_id", "wafer_key", b"wafer_key"]) -> None: ...

global___InspectionSummary = InspectionSummary

@typing.final
class ListInspectionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___InspectionSummary]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[global___InspectionSummary] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

global___ListInspectionsResponse = ListInspectionsResponse
