# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto_stubs.sc.v1 import upstream_pb2 as sc_dot_v1_dot_upstream__pb2


class ScUpstreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/sc.v1.ScUpstream/Health',
                request_serializer=sc_dot_v1_dot_upstream__pb2.HealthRequest.SerializeToString,
                response_deserializer=sc_dot_v1_dot_upstream__pb2.HealthResponse.FromString,
                )
        self.GetInspection = channel.unary_unary(
                '/sc.v1.ScUpstream/GetInspection',
                request_serializer=sc_dot_v1_dot_upstream__pb2.GetInspectionRequest.SerializeToString,
                response_deserializer=sc_dot_v1_dot_upstream__pb2.GetInspectionResponse.FromString,
                )
        self.GetInspectionPatchZips = channel.unary_unary(
                '/sc.v1.ScUpstream/GetInspectionPatchZips',
                request_serializer=sc_dot_v1_dot_upstream__pb2.GetInspectionPatchZipsRequest.SerializeToString,
                response_deserializer=sc_dot_v1_dot_upstream__pb2.GetInspectionPatchZipsResponse.FromString,
                )
        self.GetReviewImageFileSpec = channel.unary_unary(
                '/sc.v1.ScUpstream/GetReviewImageFileSpec',
                request_serializer=sc_dot_v1_dot_upstream__pb2.GetReviewImageFileSpecRequest.SerializeToString,
                response_deserializer=sc_dot_v1_dot_upstream__pb2.GetReviewImageFileSpecResponse.FromString,
                )
        self.ListReviewImages = channel.unary_unary(
                '/sc.v1.ScUpstream/ListReviewImages',
                request_serializer=sc_dot_v1_dot_upstream__pb2.ListReviewImagesRequest.SerializeToString,
                response_deserializer=sc_dot_v1_dot_upstream__pb2.ListReviewImagesResponse.FromString,
                )
        self.ListInspections = channel.unary_unary(
                '/sc.v1.ScUpstream/ListInspections',
                request_serializer=sc_dot_v1_dot_upstream__pb2.ListInspectionsRequest.SerializeToString,
                response_deserializer=sc_dot_v1_dot_upstream__pb2.ListInspectionsResponse.FromString,
                )


class ScUpstreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInspection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInspectionPatchZips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReviewImageFileSpec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReviewImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInspections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScUpstreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sc_dot_v1_dot_upstream__pb2.HealthRequest.FromString,
                    response_serializer=sc_dot_v1_dot_upstream__pb2.HealthResponse.SerializeToString,
            ),
            'GetInspection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInspection,
                    request_deserializer=sc_dot_v1_dot_upstream__pb2.GetInspectionRequest.FromString,
                    response_serializer=sc_dot_v1_dot_upstream__pb2.GetInspectionResponse.SerializeToString,
            ),
            'GetInspectionPatchZips': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInspectionPatchZips,
                    request_deserializer=sc_dot_v1_dot_upstream__pb2.GetInspectionPatchZipsRequest.FromString,
                    response_serializer=sc_dot_v1_dot_upstream__pb2.GetInspectionPatchZipsResponse.SerializeToString,
            ),
            'GetReviewImageFileSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReviewImageFileSpec,
                    request_deserializer=sc_dot_v1_dot_upstream__pb2.GetReviewImageFileSpecRequest.FromString,
                    response_serializer=sc_dot_v1_dot_upstream__pb2.GetReviewImageFileSpecResponse.SerializeToString,
            ),
            'ListReviewImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReviewImages,
                    request_deserializer=sc_dot_v1_dot_upstream__pb2.ListReviewImagesRequest.FromString,
                    response_serializer=sc_dot_v1_dot_upstream__pb2.ListReviewImagesResponse.SerializeToString,
            ),
            'ListInspections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInspections,
                    request_deserializer=sc_dot_v1_dot_upstream__pb2.ListInspectionsRequest.FromString,
                    response_serializer=sc_dot_v1_dot_upstream__pb2.ListInspectionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sc.v1.ScUpstream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScUpstream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sc.v1.ScUpstream/Health',
            sc_dot_v1_dot_upstream__pb2.HealthRequest.SerializeToString,
            sc_dot_v1_dot_upstream__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInspection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sc.v1.ScUpstream/GetInspection',
            sc_dot_v1_dot_upstream__pb2.GetInspectionRequest.SerializeToString,
            sc_dot_v1_dot_upstream__pb2.GetInspectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInspectionPatchZips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sc.v1.ScUpstream/GetInspectionPatchZips',
            sc_dot_v1_dot_upstream__pb2.GetInspectionPatchZipsRequest.SerializeToString,
            sc_dot_v1_dot_upstream__pb2.GetInspectionPatchZipsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReviewImageFileSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sc.v1.ScUpstream/GetReviewImageFileSpec',
            sc_dot_v1_dot_upstream__pb2.GetReviewImageFileSpecRequest.SerializeToString,
            sc_dot_v1_dot_upstream__pb2.GetReviewImageFileSpecResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListReviewImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sc.v1.ScUpstream/ListReviewImages',
            sc_dot_v1_dot_upstream__pb2.ListReviewImagesRequest.SerializeToString,
            sc_dot_v1_dot_upstream__pb2.ListReviewImagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListInspections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sc.v1.ScUpstream/ListInspections',
            sc_dot_v1_dot_upstream__pb2.ListInspectionsRequest.SerializeToString,
            sc_dot_v1_dot_upstream__pb2.ListInspectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
