apiVersion: v1
kind: ConfigMap
metadata:
  name: finetune-config
  namespace: finetune
data:
  APP_CONFIG_PROFILE: "dev"
  PREFECT_API_URL: "http://prefect-server.finetune.svc.cluster.local:4200/api"
  EMBEDDING_GRPC_TARGET: "embedding.finetune.svc.cluster.local:50051"
  INFERENCE_BASE_URL: "http://inference-worker.finetune.svc.cluster.local:8010"
  LLM_BASE_URL: "http://ollama.finetune.svc.cluster.local:11434/v1"
  LLM_MODEL: "llava"
  LABEL_STUDIO_URL: "http://label-studio.finetune.svc.cluster.local:8080"
  LABEL_STUDIO_EXTERNAL_URL: "http://localhost:8080"
