apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finetune
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - postgres.yaml
  - minio.yaml
  - prefect-server.yaml
  - embedding.yaml
  - inference-worker.yaml
  - label-studio.yaml
  - api-deployment.yaml
  - training-worker-gpu.yaml
  - training-worker-dspy.yaml
  - prediction-worker.yaml
  - embedding-worker.yaml
