# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10v1/service.proto\x12\x0eimageparser.v1\"\x0f\n\rHealthRequest\"(\n\x0eHealthResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\"i\n\x0fGetImageRequest\x12\x16\n\x06\x62ucket\x18\x01 \x01(\tR\x06\x62ucket\x12\x10\n\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x14\n\x05\x63\x61\x63he\x18\x04 \x01(\x08R\x05\x63\x61\x63he\"{\n\x10GetImageResponse\x12\x1d\n\nimage_data\x18\x01 \x01(\x0cR\timageData\x12\x1a\n\x08\x66ilename\x18\x02 \x01(\tR\x08\x66ilename\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\"\x7f\n\rSpriteRequest\x12\x16\n\x06\x62ucket\x18\x01 \x01(\tR\x06\x62ucket\x12\x10\n\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n\x08prefixes\x18\x03 \x03(\tR\x08prefixes\x12\x12\n\x04size\x18\x04 \x01(\x05R\x04size\x12\x14\n\x05\x63\x61\x63he\x18\x05 \x01(\x08R\x05\x63\x61\x63he\"]\n\x0eSpriteResponse\x12\x1d\n\nimage_data\x18\x01 \x01(\x0cR\timageData\x12\x14\n\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x03 \x01(\x05R\x06height\"k\n\x0fV2SpriteRequest\x12\x16\n\x06\x62ucket\x18\x01 \x01(\tR\x06\x62ucket\x12\x16\n\x06record\x18\x02 \x01(\tR\x06record\x12\x14\n\x05items\x18\x03 \x03(\tR\x05items\x12\x12\n\x04size\x18\x04 \x01(\x05R\x04size\"_\n\x10V2SpriteResponse\x12\x1d\n\nimage_data\x18\x01 \x01(\x0cR\timageData\x12\x14\n\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x03 \x01(\x05R\x06height2\xbd\x02\n\x0bImageParser\x12G\n\x06Health\x12\x1d.imageparser.v1.HealthRequest\x1a\x1e.imageparser.v1.HealthResponse\x12M\n\x08GetImage\x12\x1f.imageparser.v1.GetImageRequest\x1a .imageparser.v1.GetImageResponse\x12G\n\x06Sprite\x12\x1d.imageparser.v1.SpriteRequest\x1a\x1e.imageparser.v1.SpriteResponse\x12M\n\x08V2Sprite\x12\x1f.imageparser.v1.V2SpriteRequest\x1a .imageparser.v1.V2SpriteResponseB8Z6ft-platform/protos/gen/go/imageparser/v1;imageparserv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6ft-platform/protos/gen/go/imageparser/v1;imageparserv1'
  _HEALTHREQUEST._serialized_start=36
  _HEALTHREQUEST._serialized_end=51
  _HEALTHRESPONSE._serialized_start=53
  _HEALTHRESPONSE._serialized_end=93
  _GETIMAGEREQUEST._serialized_start=95
  _GETIMAGEREQUEST._serialized_end=200
  _GETIMAGERESPONSE._serialized_start=202
  _GETIMAGERESPONSE._serialized_end=325
  _SPRITEREQUEST._serialized_start=327
  _SPRITEREQUEST._serialized_end=454
  _SPRITERESPONSE._serialized_start=456
  _SPRITERESPONSE._serialized_end=549
  _V2SPRITEREQUEST._serialized_start=551
  _V2SPRITEREQUEST._serialized_end=658
  _V2SPRITERESPONSE._serialized_start=660
  _V2SPRITERESPONSE._serialized_end=755
  _IMAGEPARSER._serialized_start=758
  _IMAGEPARSER._serialized_end=1075
# @@protoc_insertion_point(module_scope)
