"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class HealthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthRequest: _TypeAlias = HealthRequest  # noqa: Y015

@_typing.final
class HealthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    def __init__(
        self,
        *,
        status: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HealthResponse: _TypeAlias = HealthResponse  # noqa: Y015

@_typing.final
class GetImageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUCKET_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PREFIX_FIELD_NUMBER: _builtins.int
    CACHE_FIELD_NUMBER: _builtins.int
    bucket: _builtins.str
    key: _builtins.str
    prefix: _builtins.str
    cache: _builtins.bool
    def __init__(
        self,
        *,
        bucket: _builtins.str = ...,
        key: _builtins.str = ...,
        prefix: _builtins.str = ...,
        cache: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket", b"bucket", "cache", b"cache", "key", b"key", "prefix", b"prefix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetImageRequest: _TypeAlias = GetImageRequest  # noqa: Y015

@_typing.final
class GetImageResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    filename: _builtins.str
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        filename: _builtins.str = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename", "height", b"height", "image_data", b"image_data", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetImageResponse: _TypeAlias = GetImageResponse  # noqa: Y015

@_typing.final
class SpriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUCKET_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    PREFIXES_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    CACHE_FIELD_NUMBER: _builtins.int
    bucket: _builtins.str
    key: _builtins.str
    size: _builtins.int
    cache: _builtins.bool
    @_builtins.property
    def prefixes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        bucket: _builtins.str = ...,
        key: _builtins.str = ...,
        prefixes: _abc.Iterable[_builtins.str] | None = ...,
        size: _builtins.int = ...,
        cache: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket", b"bucket", "cache", b"cache", "key", b"key", "prefixes", b"prefixes", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpriteRequest: _TypeAlias = SpriteRequest  # noqa: Y015

@_typing.final
class SpriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "image_data", b"image_data", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpriteResponse: _TypeAlias = SpriteResponse  # noqa: Y015

@_typing.final
class V2SpriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BUCKET_FIELD_NUMBER: _builtins.int
    RECORD_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    bucket: _builtins.str
    record: _builtins.str
    size: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        bucket: _builtins.str = ...,
        record: _builtins.str = ...,
        items: _abc.Iterable[_builtins.str] | None = ...,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bucket", b"bucket", "items", b"items", "record", b"record", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___V2SpriteRequest: _TypeAlias = V2SpriteRequest  # noqa: Y015

@_typing.final
class V2SpriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    image_data: _builtins.bytes
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        image_data: _builtins.bytes = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "image_data", b"image_data", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___V2SpriteResponse: _TypeAlias = V2SpriteResponse  # noqa: Y015
