"""prune legacy worker deployments

Revision ID: 28010cffc0bc
Revises: 6c6df75eb294
Create Date: 2026-05-28 20:34:31.002468

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '28010cffc0bc'
down_revision = '6c6df75eb294'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Prune legacy deployment rows (registered by serve_flows())
    # Wrapped in DO block so migration succeeds when Prefect tables don't exist yet
    op.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'deployment') THEN
                DELETE FROM deployment WHERE name IN (
                    'train-job-deployment',
                    'predict-job-deployment',
                    'train-job-torch-deployment',
                    'train-job-dspy-deployment',
                    'predict-job-batch-deployment',
                    'embed-job-batch-deployment',
                    'sc-import-deployment'
                );
            END IF;

            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'work_pool') THEN
                DELETE FROM work_pool WHERE name IN (
                    'training-pool',
                    'default-pool',
                    'default',
                    'train-gpu',
                    'optimize-llm-cpu',
                    'predict-batch',
                    'embed-batch'
                );
            END IF;
        END $$;
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: data loss is intentional; prepare_platform.py re-registers deployments.
    pass
    # ### end Alembic commands ###
