"""initial_schema

Revision ID: 6c6df75eb294
Revises:
Create Date: 2026-05-24 20:29:30.667524

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6c6df75eb294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sensor_checkpoints',
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('watermark', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('sensor_subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('filter_config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_type', sa.String(length=64), nullable=False),
    sa.Column('view_types', sa.JSON(), nullable=False),
    sa.Column('dataset_meta', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embed_config', sa.JSON(), nullable=True),
    sa.Column('ls_project_id', sa.String(length=255), nullable=False),
    sa.Column('storage_mode', sa.String(length=64), server_default='db_full', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id')
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('prefect_deployment_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('flow_name', sa.String(length=255), nullable=False),
    sa.Column('cron', sa.String(length=255), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_schedule_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('sample_ids', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_job_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('image_uris', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ls_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('trainer_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_job_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('annotation_value', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_table('job_user_state',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('user_left', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('platform_predictions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('predicted_label', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('all_scores_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['prediction_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_predictions_created_at'), 'platform_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_predictions_dataset_id'), 'platform_predictions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_platform_predictions_job_id'), 'platform_predictions', ['job_id'], unique=False)
    op.create_index(op.f('ix_platform_predictions_model_id'), 'platform_predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_platform_predictions_model_version'), 'platform_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_platform_predictions_org_id'), 'platform_predictions', ['org_id'], unique=False)
    op.create_index(op.f('ix_platform_predictions_sample_id'), 'platform_predictions', ['sample_id'], unique=False)
    op.create_table('prediction_collections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('source_job_id', sa.String(length=64), nullable=True),
    sa.Column('sync_tag', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_job_id'], ['prediction_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_collections_dataset_id'), 'prediction_collections', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_prediction_collections_model_id'), 'prediction_collections', ['model_id'], unique=False)
    op.create_index(op.f('ix_prediction_collections_org_id'), 'prediction_collections', ['org_id'], unique=False)
    op.create_index(op.f('ix_prediction_collections_source_job_id'), 'prediction_collections', ['source_job_id'], unique=False)
    op.create_table('prediction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['prediction_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_events_job_id'), 'prediction_events', ['job_id'], unique=False)
    op.create_table('sample_features',
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embed_model', sa.String(length=255), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('training_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_events_job_id'), 'training_events', ['job_id'], unique=False)
    op.create_table('prediction_collection_items',
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('prediction_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['prediction_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['platform_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'prediction_id')
    )
    op.create_table('prediction_review_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('collection_id', sa.String(length=64), nullable=True),
    sa.Column('sync_tag', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['prediction_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_review_actions_collection_id'), 'prediction_review_actions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_prediction_review_actions_dataset_id'), 'prediction_review_actions', ['dataset_id'], unique=False)
    op.create_table('annotation_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('review_action_id', sa.String(length=64), nullable=False),
    sa.Column('annotation_id', sa.String(length=64), nullable=False),
    sa.Column('prediction_id', sa.String(length=64), nullable=True),
    sa.Column('predicted_label', sa.String(length=255), nullable=False),
    sa.Column('final_label', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['platform_predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_action_id'], ['prediction_review_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_versions_annotation_id'), 'annotation_versions', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_versions_prediction_id'), 'annotation_versions', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_annotation_versions_review_action_id'), 'annotation_versions', ['review_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_versions_review_action_id'), table_name='annotation_versions')
    op.drop_index(op.f('ix_annotation_versions_prediction_id'), table_name='annotation_versions')
    op.drop_index(op.f('ix_annotation_versions_annotation_id'), table_name='annotation_versions')
    op.drop_table('annotation_versions')
    op.drop_index(op.f('ix_prediction_review_actions_dataset_id'), table_name='prediction_review_actions')
    op.drop_index(op.f('ix_prediction_review_actions_collection_id'), table_name='prediction_review_actions')
    op.drop_table('prediction_review_actions')
    op.drop_table('prediction_collection_items')
    op.drop_index(op.f('ix_training_events_job_id'), table_name='training_events')
    op.drop_table('training_events')
    op.drop_table('sample_features')
    op.drop_index(op.f('ix_prediction_events_job_id'), table_name='prediction_events')
    op.drop_table('prediction_events')
    op.drop_index(op.f('ix_prediction_collections_source_job_id'), table_name='prediction_collections')
    op.drop_index(op.f('ix_prediction_collections_org_id'), table_name='prediction_collections')
    op.drop_index(op.f('ix_prediction_collections_model_id'), table_name='prediction_collections')
    op.drop_index(op.f('ix_prediction_collections_dataset_id'), table_name='prediction_collections')
    op.drop_table('prediction_collections')
    op.drop_index(op.f('ix_platform_predictions_sample_id'), table_name='platform_predictions')
    op.drop_index(op.f('ix_platform_predictions_org_id'), table_name='platform_predictions')
    op.drop_index(op.f('ix_platform_predictions_model_version'), table_name='platform_predictions')
    op.drop_index(op.f('ix_platform_predictions_model_id'), table_name='platform_predictions')
    op.drop_index(op.f('ix_platform_predictions_job_id'), table_name='platform_predictions')
    op.drop_index(op.f('ix_platform_predictions_dataset_id'), table_name='platform_predictions')
    op.drop_index(op.f('ix_platform_predictions_created_at'), table_name='platform_predictions')
    op.drop_table('platform_predictions')
    op.drop_table('job_user_state')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('annotations')
    op.drop_table('training_jobs')
    op.drop_table('samples')
    op.drop_table('prediction_jobs')
    op.drop_table('schedules')
    op.drop_table('personal_access_tokens')
    op.drop_table('org_memberships')
    op.drop_table('datasets')
    op.drop_table('users')
    op.drop_table('sensor_subscriptions')
    op.drop_table('sensor_checkpoints')
    op.drop_table('organizations')
    # ### end Alembic commands ###
