[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "proto-stubs"
version = "0.1.0"
description = "Generated protobuf stubs"
requires-python = ">=3.11"
dependencies = ["grpcio==1.80.0", "protobuf==6.33.6"]

[project.optional-dependencies]
codegen = ["grpcio-tools==1.80.0"]

[tool.uv.build-backend]
module-name = "proto_stubs"
